name: nostaclone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.7
  hive_flutter: ^1.1.0
  http: ^1.2.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/